In [568]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from warnings import filterwarnings
filterwarnings('ignore')
from sklearn import metrics as sm
from sklearn import preprocessing as sp

In [569]:
df = pd.read_csv('Titanic-Dataset.csv')

In [570]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [571]:
df['Cabin'] = df['Cabin'].notna().astype(int)

In [572]:
df['Is_Master'] = df['Name'].apply(ismaster)

In [573]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    int64
 11  Embarked     889 non-null    str
 12  Is_Master    891 non-null    int64
dtypes: float64(2), int64(7), str(4)
memory usage: 90.6 KB

In [574]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Master
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,0,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q,0

In [575]:
def ismaster(x : str):
    if(x.count("Master") > 0):
        return 1
    return 0

In [576]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Master
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,0,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q,0

In [577]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Master
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,0,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q,0

In [578]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    int64
 11  Embarked     889 non-null    str
 12  Is_Master    891 non-null    int64
dtypes: float64(2), int64(7), str(4)
memory usage: 90.6 KB

In [579]:
df['Age'].median()

np.float64(28.0)

In [580]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [581]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    int64
 11  Embarked     889 non-null    str
 12  Is_Master    891 non-null    int64
dtypes: float64(2), int64(7), str(4)
memory usage: 90.6 KB

In [582]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [583]:
df = df.drop(columns = ['Cabin']).dropna()

In [584]:
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(columns = ['Survived']), df['Survived'], test_size=0.2,random_state=43)

In [585]:
X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Is_Master
630,631,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,S,0
839,840,1,"Marechal, Mr. Pierre",male,28.0,0,0,11774,29.7000,C,0
613,614,3,"Horgan, Mr. John",male,28.0,0,0,370377,7.7500,Q,0
189,190,3,"Turcin, Mr. Stjepan",male,36.0,0,0,349247,7.8958,S,0
110,111,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,S,0
...,...,...,...,...,...,...,...,...,...,...,...
278,279,3,"Rice, Master. Eric",male,7.0,4,1,382652,29.1250,Q,1
818,819,3,"Holm, Mr. John Fredrik Alexander",male,43.0,0,0,C 7075,6.4500,S,0
256,257,1,"Thorne, Mrs. Gertrude Maybelle",female,28.0,0,0,PC 17585,79.2000,C,0
321,322,3,"Danoff, Mr. Yoto",male,27.0,0,0,349219,7.8958,S,0
838,839,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,S,0

In [586]:
#X_train['Ticket_Cat'] = X_train['Ticket'].apply(lambda x : 0 if x.isnumeric() else 1)

In [587]:
#X_test['Ticket_Cat'] = X_test['Ticket'].apply(lambda x : 0 if x.isnumeric() else 1)

In [588]:
X_train.drop(columns = ['PassengerId', 'Ticket'], inplace=True)

In [589]:
X_test.drop(columns = ['PassengerId', 'Ticket'], inplace=True)

In [590]:
pd.get_dummies(X_train[['Sex', 'Embarked']], drop_first=True, dtype=int)

     Sex_male  Embarked_Q  Embarked_S
630         1           0           1
839         1           0           0
613         1           1           0
189         1           0           1
110         1           0           1
..        ...         ...         ...
278         1           1           0
818         1           0           1
256         0           0           0
321         1           0           1
838         1           0           1

[711 rows x 3 columns]

In [591]:
X_train = X_train.merge(pd.get_dummies(X_train[['Sex', 'Embarked']], drop_first=True, dtype=int), left_index=True, right_index=True).drop(columns = ['Sex', 'Embarked', 'Name'])

In [592]:
X_train

,Pclass,Age,SibSp,Parch,Fare,Is_Master,Sex_male,Embarked_Q,Embarked_S
630,1,80.0,0,0,30.0000,0,1,0,1
839,1,28.0,0,0,29.7000,0,1,0,0
613,3,28.0,0,0,7.7500,0,1,1,0
189,3,36.0,0,0,7.8958,0,1,0,1
110,1,47.0,0,0,52.0000,0,1,0,1
...,...,...,...,...,...,...,...,...,...
278,3,7.0,4,1,29.1250,1,1,1,0
818,3,43.0,0,0,6.4500,0,1,0,1
256,1,28.0,0,0,79.2000,0,0,0,0
321,3,27.0,0,0,7.8958,0,1,0,1
838,3,32.0,0,0,56.4958,0,1,0,1

In [593]:
X_test = X_test.merge(pd.get_dummies(X_test[['Sex', 'Embarked']], drop_first=True, dtype=int), left_index=True, right_index=True).drop(columns = ['Sex', 'Embarked', 'Name'])

In [594]:
X_train.describe()

,Pclass,Age,SibSp,Parch,Fare,Is_Master,Sex_male,Embarked_Q,Embarked_S
count,711.000000,711.000000,711.000000,711.000000,711.000000,711.000000,711.000000,711.000000,711.000000
mean,2.305204,29.481252,0.531646,0.389592,32.772579,0.050633,0.651195,0.090014,0.713080
std,0.838149,13.320584,1.090960,0.809349,51.816239,0.219401,0.476927,0.286403,0.452642
min,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,22.000000,0.000000,0.000000,7.925000,0.000000,0.000000,0.000000,0.000000
50%,3.000000,28.000000,0.000000,0.000000,15.000000,0.000000,1.000000,0.000000,1.000000
75%,3.000000,35.000000,1.000000,0.000000,30.847900,0.000000,1.000000,0.000000,1.000000
max,3.000000,80.000000,8.000000,5.000000,512.329200,1.000000,1.000000,1.000000,1.000000

In [595]:
X_train['Age'].value_counts()

Age
28.00    159
24.00     23
30.00     22
36.00     19
22.00     19
        ...
55.50      1
30.50      1
55.00      1
0.92       1
43.00      1
Name: count, Length: 86, dtype: int64

In [596]:
X_train['Age'].astype(int)

630    80
839    28
613    28
189    36
110    47
       ..
278     7
818    43
256    28
321    27
838    32
Name: Age, Length: 711, dtype: int64

In [597]:
Y_train.loc[X_train[(X_train['Age'] < 35) & (X_train['Age'] > 25)].index].sum()

np.int64(97)

In [598]:
def categorize(x):
    if(x < 5):
        return 1
    if(x < 15):
        return 2
    if(x < 20):
        return 3
    if(x < 25):
        return 4
    if(x < 30):
        return 5
    if(x < 35):
        return 6
    if(x < 40):
        return 7
    if(x < 50):
        return 8
    if(x < 60):
        return 9
    if(x >= 60):
        return 10

In [599]:
X_train['Age']=X_train['Age'].apply(categorize)

In [600]:
X_test['Age'] = X_test['Age'].apply(categorize)

In [601]:
X_train

,Pclass,Age,SibSp,Parch,Fare,Is_Master,Sex_male,Embarked_Q,Embarked_S
630,1,10,0,0,30.0000,0,1,0,1
839,1,5,0,0,29.7000,0,1,0,0
613,3,5,0,0,7.7500,0,1,1,0
189,3,7,0,0,7.8958,0,1,0,1
110,1,8,0,0,52.0000,0,1,0,1
...,...,...,...,...,...,...,...,...,...
278,3,2,4,1,29.1250,1,1,1,0
818,3,8,0,0,6.4500,0,1,0,1
256,1,5,0,0,79.2000,0,0,0,0
321,3,5,0,0,7.8958,0,1,0,1
838,3,6,0,0,56.4958,0,1,0,1

In [602]:
X_test

,Pclass,Age,SibSp,Parch,Fare,Is_Master,Sex_male,Embarked_Q,Embarked_S
333,3,3,2,0,18.0000,0,1,0,1
546,2,3,1,0,26.0000,0,0,0,1
533,3,5,0,2,22.3583,0,0,0,0
449,1,9,0,0,30.5000,0,1,0,1
677,3,3,0,0,9.8417,0,0,0,1
...,...,...,...,...,...,...,...,...,...
72,2,4,0,0,73.5000,0,1,0,1
560,3,5,0,0,7.7500,0,1,1,0
787,3,2,4,1,29.1250,1,1,1,0
648,3,5,0,0,7.5500,0,1,0,1
564,3,5,0,0,8.0500,0,0,0,1

In [603]:
lr = LogisticRegression()

In [604]:
lr.fit(X_train, Y_train)

LogisticRegression()

In [605]:
lr.score(X_train, Y_train)

0.8340365682137834

In [606]:
lr.score(X_test, Y_test)

0.8370786516853933

In [607]:
sm.balanced_accuracy_score(Y_train,lr.predict(X_train))

0.8159545424092188